### ISSUE TITLE
Cheating by keep pressing key

### ISSUE THREAD

**Issue by ZtianWisc** [jonhoo/tetris-tutorial#12]
Thank you so much for your code and explanation. It really helped me a lot getting started with js. 
One tiny suggestion here: the Piece drop one square every second now, however when key is pressed, _dropStart = Data.now()_, so that if I keep pressing key, dropStart will be re-zeroed and the shape will never drop. Maybe delete _dropStart = Data.now()_ when key is pressed? I could be wrong tho.

**Comment by jonhoo** [comment]
I'm not sure what the "correct" Tetris behavior is, nor do I remember why that line is there in the first place. I'm tempted to leave it in though just in case removing it breaks something else :laughing: I'm glad you've found the tutorial helpful though!
