### ISSUE TITLE
Concerns about "The memory [..] is, in most cases [..] initialized to all 0s."

### ISSUE THREAD

**Issue by hartwork** [jonhoo/tetris-tutorial#6]
Hi!
I worry about that the

> The memory an application can see is, in most cases, private to the application, and initialized to all 0s. 

in `doc/code.md` could make the reader blind to uninitialized variable problems of other languages, especially C. I would like to propose adding "at least in JavaScript" or so. That would ensure that at least high attention readers get the does-not-apply-everywhere bit.

Excellent tutorial by the way, well done!

**Comment by jonhoo** [comment]
Glad you enjoyed it, and thanks for the detailed feedback. Any other thoughts you have, feel free to send them my way :)

**Comment by hartwork** [comment]
Thanks for the fix, very nice.
