### ISSUE TITLE
Last piece remains movable after clicking "You're done!"

### ISSUE THREAD

**Issue by hartwork** [jonhoo/tetris-tutorial#7]
After clicking "You're done!" I happen to be able to still control that last killing block with "gravity" turned off. I'm on Firefox 39.0.3 if that matters.

**Comment by jonhoo** [comment]
I've pushed a fix now. Could you see if this resolves the problem for you?

**Comment by hartwork** [comment]
Yes, db0b589d9bae26bc77df92dbc48e3576a796e34f seems to have fixed the issue.

**Comment by jonhoo** [comment]
Closed in db0b589d9bae26bc77df92dbc48e3576a796e34f
